### PR TITLE
Only list hackathons in digests every 3 months if it's more than a month out

### PR DESCRIPTION
**Pull request by northeastprince**

### CODE REVIEW

**Review by garyhtou — APPROVED** [review]
I like this idea! To make sure we're on the same page:
- If hackathon is less than 1 month from now, list it every time
- If hackathon is more than 1 month from now, list it every 3 months

Maybe we should update it to every 1 month

**Comment by garyhtou** [comment]
Another way to approach this problem is:

```ruby
# sudo code

def black_list # there's prob a better name
  # hackathons that are more than 1 month away and have been listed within the past 3 months for this recipient
end

applicable_listings.remove(black_list).first(MAX_LISTINGS)
```

This would make fewer queries to the DB I think

**Review by flexcommits — APPROVED** [review]
you are great!!!

**Comment by garyhtou** [comment]
Is there anything blocking this PR?

**Pull request merged**
