### PR TITLE
Serve images directly so they can be cached

### PR DESCRIPTION
**Pull request by northeastprince**
We'd probably want a CDN to take full advantage of this.

### CODE REVIEW

**Review by garyhtou — COMMENTED** [review]
Could you help me understand what is the problem we're trying to solve?

My assumption (and please correct me if I'm wrong) is that the majority of the requests are to `ActiveStorage::Representations::RedirectController#show` and we want to reduce that. are we on the same page?

**Review by flexcommits — COMMENTED** [review]
Could you help me understand what is the problem we're trying to solve?

**Comment by garyhtou** [comment]
Got it! What are the pros and cons of this solution compared to Active Storage's proxy mode?

https://guides.rubyonrails.org/active_storage_overview.html#proxy-mode

---

re: emailed digests. Yeah, I agree! From my understanding, most email servers end up storing images on their own servers to prevent email pixel tracking; so we don't need to worry about the load from emailed digests.

**Comment by garyhtou** [comment]
Something I'm curious about is what would it take to set up Cloudflare in front of Hackathons Backend? I'm asking about this because I'd like to explore setting up Cloudflare for [HCB](https://github.com/hackclub/hcb) in the future. Our DNS is managed in https://github.com/hackclub/dns which might make it difficult to integrate with Cloudflare.

**Comment by northeastprince** [comment]
@garyhtou yeah, proxy mode seems like a better way to do it. Regarding Cloudflare, I'm pretty sure the one thing we were waiting on to switch from DNSimple to Cloudflare was upgrading OctoDNS to the latest version, but @cjdenio ran into some issues with that which I don't remember.

**Comment by northeastprince** [comment]
Not sure what I was thinking here - as long as the additional S3 costs aren't notable, the current setup (offloading serving directly to AWS) should be fine for now.

**Pull request closed without merging**
